steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/dart-ci/github-label-notifier', '.']
- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/dart-ci/github-label-notifier']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'github-webhook', '--image', 'gcr.io/dart-ci/github-label-notifier', '--region', 'us-central1']
