# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [lib/src/generated/**, third_party/**]

linter:
  rules:
    # Disabled - TODO(athom): enable after results_feed port is finished.
    avoid_print: false
    directives_ordering: true
    prefer_relative_imports: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
