name: flutter_current_results
description: A Flutter web UI that fetches and shows current test results

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1
  grpc: ^3.1.0
  http: ^0.13.4
  intl: ^0.18.1
  protobuf: ^2.0.1
  provider: ^6.0.2
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true # Includes material icons
  assets:
  - assets/
