name: flutter_current_results
description: A Flutter web UI that fetches and shows current test results

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  clippy: ^1.0.0
  flutter:
    sdk: flutter

  http: ^0.13.1
  grpc: ^3.0.0
  protobuf: ^2.0.0
  provider: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true # Includes material icons
  assets:
  - assets/
