name: flutter_current_results
description: A Flutter web UI that fetches and shows current test results

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  build_runner: ^2.4.15
  collection: ^1.17.1
  firebase_auth: ^5.1.4 # Add firebase_auth
  firebase_core: ^3.2.0 # Add firebase_core
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  grpc: ^4.0.4
  http: ^1.3.0
  intl: ^0.20.2
  mockito: ^5.4.6
  protobuf: ^4.0.0
  provider: ^6.0.2
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore: ^5.6.7

flutter:
  uses-material-design: true # Includes material icons
  assets:
  - assets/
