name: flutter_current_results
description: A Flutter web UI that fetches and shows current test results

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.2.0
  http: ^1.5.0
  intl: ^0.20.2
  protobuf: ^4.0.0
  provider: ^6.0.2
  url_launcher: ^6.0.20

dev_dependencies:
  build_runner: ^2.6.0
  firebase_auth_platform_interface: ^8.1.0
  firebase_core_platform_interface: ^6.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.5.0

flutter:
  uses-material-design: true # Includes material icons
  assets:
  - assets/
